In [2]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import random

In [3]:
def generate_random_data(n_samples, n_features, min_val=0, max_val=10):
    return np.random.uniform(min_val, max_val, (n_samples, n_features))

In [4]:
def create_adjacency_matrix(data, k):
    n_samples = len(data)
    knn = NearestNeighbors(n_neighbors=k+1)
    knn.fit(data)

    _, indices = knn.kneighbors(data)
    adj_matrix = np.zeros((n_samples, n_samples))

    for i in range(n_samples):
        for j in indices[i][1:]:
            adj_matrix[i][j] = 1

    return adj_matrix

In [5]:
def calculate_scores(adj_matrix):
    n_samples = len(adj_matrix)
    nn_scores = np.zeros(n_samples)
    mnn_scores = np.zeros(n_samples)

    for i in range(n_samples):
        for j in range(n_samples):
            if i != j and adj_matrix[j][i] == 1:
                nn_scores[i] += 1
                if adj_matrix[i][j] == 1:
                    mnn_scores[i] += 1

    return nn_scores, mnn_scores

In [7]:
k = 2
n_samples = 5
n_features = 2

data = generate_random_data(n_samples, n_features)
adj_matrix = create_adjacency_matrix(data, k)
nn_scores, mnn_scores = calculate_scores(adj_matrix)

results = pd.DataFrame({
    'Feature_1': data[:, 0],
    'Feature_2': data[:, 1],
    'NN Score': nn_scores,
    'MNN Score': mnn_scores
})

print("\nRandom Data Points:")
print(data)
print("\nAdjacency Matrix:")
print(adj_matrix)
print("\nScores:")
print(results)

print("\nDetails:")
for i in range(n_samples):
    neighbors = np.where(adj_matrix[i] == 1)[0]
    print(f"Point {i} neighbors: {neighbors}")
    print(f"NN Score: {nn_scores[i]}")
    print(f"MNN Score: {mnn_scores[i]}")
    print()


Random Data Points:
[[8.92042112 1.1917227 ]
 [4.0274711  0.79674044]
 [3.35274719 4.82766011]
 [5.80403835 9.94593805]
 [0.07072737 9.35997112]]

Adjacency Matrix:
[[0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0.]]

Scores:
   Feature_1  Feature_2  NN Score  MNN Score
0   8.920421   1.191723       1.0        1.0
1   4.027471   0.796740       2.0        2.0
2   3.352747   4.827660       4.0        2.0
3   5.804038   9.945938       1.0        1.0
4   0.070727   9.359971       2.0        2.0

Details:
Point 0 neighbors: [1 2]
NN Score: 1.0
MNN Score: 1.0

Point 1 neighbors: [0 2]
NN Score: 2.0
MNN Score: 2.0

Point 2 neighbors: [1 4]
NN Score: 4.0
MNN Score: 2.0

Point 3 neighbors: [2 4]
NN Score: 1.0
MNN Score: 1.0

Point 4 neighbors: [2 3]
NN Score: 2.0
MNN Score: 2.0

